### ISSUE TITLE
Cant connect hue essential app

### ISSUE THREAD

**Issue by Joly0** [maxbec/hassio-diyHue#42]
I am trying to connect the hue essentials app with this diyhue hassio addon but i cant get it to work. 
In the home assistant addon log i keep getting this:
`[2022-03-01 16:56:04,161] ERROR in app: Exception on /api/hueessac997811ecbbbb525400894582 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/restful.py", line 116, in get
    result[resource][resource_id] = bridgeConfig[resource][resource_id].getV1Api(
  File "/opt/hue-emulator/HueObjects/__init__.py", line 331, in getV1Api
    result["state"]["hue"] = self.state["hue"]
KeyError: 'hue'`

and in the hue essentials app i get this error:
`Server error(GET https://192.168.178.236/api/hueessac997811ecbbbb525400894582: 500
INTERNAL SERVER ERROR. Text:"{"message":"Internal Server Error"}"`

**Comment by Mevel** [comment]
I would like to invite you to the official diyhue-hassio addon repo found here

https://github.com/diyhue/hassio-addon

it is based upon this repo and will be maintained officially.

Let me know if this resolved your issue
